# ActionSMTP Configuration File
# Copy this file to config.yml and customize for your setup

# SMTP Server Settings
server:
  port: 25
  host: "0.0.0.0"
  maxSize: 26214400  # 25MB in bytes
  timeout: 30000     # milliseconds
  
  # Server hostname for HELO/EHLO responses (optional)
  # This should match the PTR (reverse DNS) record for your server's IP address
  # If not specified, defaults to the system's hostname
  # Example: mail.example.com
  # hostname: "mail.example.com"
  
# Webhook Configuration
#
# You can define multiple webhooks for different domains/subdomains.
# The first webhook that matches the domain will be used.
webhooks:
  example.org, example.com:
    url: "http://localhost:3000/rails/action_mailbox/relay/inbound_emails"
    
    # Basic Authentication (optional)
    auth:
      user: "actionmailbox"
      pass: "set your password here"

  # Wildcard (*) route for every subdomain of mydomain.org
  # "*.mydomain.org":
  #   url: "http://localhost:3000/rails/action_mailbox/relay/inbound_emails"

  # Wildcard (*) route for every domain fallback domains. 
  # This is NOT RECOMMENDED as it'll route every email received to your Rails application and 
  # will likely lead to a lot of spam and abuse.
  # "*":
  #  url: "http://localhost:3000/rails/action_mailbox/relay/inbound_emails"

# Spam Filtering Configuration
spam:
  enabled: true
  
  # SpamAssassin Settings
  spamassassin:
    host: "localhost"
    port: 783
    
  # DNSBL (DNS Blacklist) Settings
  dnsbl:
    enabled: true
    servers:
      - "zen.spamhaus.org"    # Spamhaus combined list
      - "bl.spamcop.net"      # SpamCop blacklist
    timeout: 3000             # DNS query timeout in milliseconds per server
    dns_servers:              # DNS servers (used as fallbacks if first fails)
      - "8.8.8.8"             # Google DNS primary
      - "8.8.4.4"             # Google DNS secondary
    
  # Spam Thresholds
  thresholds:
    flag: 5.0      # Score at which to flag as spam
    reject: 10.0   # Score at which to reject email
    
# Logging
logging:
  verbose: false